### PR TITLE
Fix python and open ssl

### PR DESCRIPTION
**Pull request by notFloran**
See https://github.com/TheGrowingPlant/mac-playbook/issues/53#issuecomment-600485434

### CODE REVIEW

**Comment by notFloran** [comment]
To check if you have the issue, execute python cli and `import psycopg2`

**Comment by nclsHart** [comment]
For the moment, I even not need to do this, `dev setup` is instantly crashing.

**Comment by notFloran** [comment]
> For the moment, I even not need to do this, `dev setup` is instantly crashing.

What I have you done

**Comment by nclsHart** [comment]
I have just upgraded to Catalina last night 🙄.
It's ok and it have also fixed my python crash.

**Pull request merged**
